# Generated by Django 4.2.1 on 2023-06-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstatesLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'real_estates_links',
                'managed': False,
            },
        ),
    ]
