# Generated by Django 4.2.1 on 2023-06-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0002_realestateslinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealEstatesLinks',
        ),
    ]
